resources:
- name: ci
  type: git
  source:
    branch: master
    uri: https://github.com/nehagjain15/ci_pipeline.git
jobs:
- name: random
  plan:
  - get: ci
    trigger: true
  - task: run
    file: ci/tasks/run.yml
- name: scareaway
  plan:
  - get: ci 
    trigger: true
    passed: [random]
  - task: scare
    file: ci/tasks/scare.yml
